version: "2"
services:
  webserver:
    image: ethan-dbdl-webserver
    ports:
      - "80:80"
    env_file:
      - "C:\\Users\\harri\\Documents\\ethan-dbdl-webserver.env"
    depends_on:
      - mysql
    networks:
      - my-network
    volumes:
      - c:/dev/dbdl-perk-randomizer-app/src:/var/www/html
    entrypoint: /opt/setup.sh
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      "C:\\Users\\harri\\Documents\\ethan-dbdl-mysql.env"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql_data:
