version: "2"
services:
  webserver:
    image: ethan-dbdl-webserver
    ports:
      - "443:443"
    env_file:
      - "C:\\Users\\harri\\Documents\\ethan-dbdl-webserver.env"
    depends_on:
      - mysql
    networks:
      - my-network
    volumes:
      - c:/dev/dbdl-perk-randomizer-app/ssl:/etc/pki/tls/certs/rockymountaintechlab.com
    entrypoint: /var/www/dbdl-laravel-app/setup.sh
  mysql:
    image: mysql:latest
    env_file:
      "C:\\Users\\harri\\Documents\\ethan-dbdl-mysql.env"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql_data:
